server {
  listen 80;
  root /usr/share/nginx/html;

  # SPA / expo-router fallback: sirve el .html correspondiente o cae a index.html
  location / {
    try_files $uri $uri.html $uri/ /index.html;
  }
}
